name: ✨ Feature Request
description: Suggest a new feature or enhancement for OpsSight
title: "[Feature]: "
labels: [enhancement, triage]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please help us understand your use case.

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Dashboard Component
        - API Enhancement
        - UI/UX Improvement
        - Performance Enhancement
        - Security Feature
        - Documentation
        - Developer Experience
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: "I'm frustrated when... / It would be helpful if... / Users need..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: "Other options might include..."

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples to illustrate your feature
      placeholder: "Drag and drop images here or provide links to examples"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for our use case
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple change or addition
        - Medium - Moderate effort required
        - High - Significant development effort
        - Unknown - Not sure about complexity

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, links, or information about the feature request
      placeholder: "Any additional information that might be helpful..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: This feature aligns with OpsSight's DevOps visibility mission
          required: true