"""Add granted_by field to user_permissions table

Revision ID: 3fd5b7393728
Revises: e988b93edd68
Create Date: 2025-07-11 18:37:00.163116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd5b7393728'
down_revision: Union[str, None] = 'e988b93edd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_permissions', sa.Column('granted_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_permissions_granted_by'), 'user_permissions', ['granted_by'], unique=False)
    op.create_foreign_key(None, 'user_permissions', 'users', ['granted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.drop_index(op.f('ix_user_permissions_granted_by'), table_name='user_permissions')
    op.drop_column('user_permissions', 'granted_by')
    # ### end Alembic commands ###
