"""implement_audit_logging_system

Revision ID: 80bd6a3c3fa1
Revises: b521a10e8182
Create Date: 2025-06-11 10:58:45.390602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80bd6a3c3fa1"
down_revision: Union[str, None] = "b521a10e8182"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "INSERT",
                "UPDATE",
                "DELETE",
                "SELECT",
                "LOGIN",
                "LOGOUT",
                "PERMISSION_CHANGE",
                "EXPORT",
                "IMPORT",
                name="auditoperation",
            ),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("include_old_values", sa.Boolean(), nullable=False),
        sa.Column("include_new_values", sa.Boolean(), nullable=False),
        sa.Column(
            "excluded_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "sensitive_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "required_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column(
            "severity_override",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="auditseverity"),
            nullable=True,
        ),
        sa.Column("category_override", sa.String(length=50), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_config_lookup",
        "audit_configurations",
        ["table_name", "operation"],
        unique=False,
    )
    op.create_index(
        "ix_audit_config_unique",
        "audit_configurations",
        ["organization_id", "table_name", "operation"],
        unique=True,
    )
    op.create_index(
        op.f("ix_audit_configurations_id"), "audit_configurations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_configurations_operation"),
        "audit_configurations",
        ["operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_configurations_organization_id"),
        "audit_configurations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_configurations_table_name"),
        "audit_configurations",
        ["table_name"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "operation",
            sa.Enum(
                "INSERT",
                "UPDATE",
                "DELETE",
                "SELECT",
                "LOGIN",
                "LOGOUT",
                "PERMISSION_CHANGE",
                "EXPORT",
                "IMPORT",
                name="auditoperation",
            ),
            nullable=False,
        ),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("record_id", sa.String(length=50), nullable=True),
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="auditseverity"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "additional_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("api_endpoint", sa.String(length=200), nullable=True),
        sa.Column("http_method", sa.String(length=10), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("sensitivity_level", sa.String(length=20), nullable=True),
        sa.Column(
            "retention_until", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_audit_id"), "audit_logs", ["audit_id"], unique=True
    )
    op.create_index(
        op.f("ix_audit_logs_category"), "audit_logs", ["category"], unique=False
    )
    op.create_index(
        "ix_audit_logs_context_gin",
        "audit_logs",
        ["additional_context"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"additional_context": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_audit_logs_correlation",
        "audit_logs",
        ["correlation_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_correlation_id"),
        "audit_logs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        "ix_audit_logs_new_values_gin",
        "audit_logs",
        ["new_values"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"new_values": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_audit_logs_old_values_gin",
        "audit_logs",
        ["old_values"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"old_values": "jsonb_path_ops"},
    )
    op.create_index(
        op.f("ix_audit_logs_operation"), "audit_logs", ["operation"], unique=False
    )
    op.create_index(
        "ix_audit_logs_operation_time",
        "audit_logs",
        ["operation", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_org_time",
        "audit_logs",
        ["organization_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"),
        "audit_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_record_id"), "audit_logs", ["record_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_record_lookup",
        "audit_logs",
        ["table_name", "record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_session_id"), "audit_logs", ["session_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_session_tracking",
        "audit_logs",
        ["session_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_severity"), "audit_logs", ["severity"], unique=False
    )
    op.create_index(
        "ix_audit_logs_severity_time",
        "audit_logs",
        ["severity", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_table_name"), "audit_logs", ["table_name"], unique=False
    )
    op.create_index(
        "ix_audit_logs_table_time",
        "audit_logs",
        ["table_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_user_time", "audit_logs", ["user_id", "timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_logs_user_time", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_table_time", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_table_name"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_severity_time", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_severity"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_session_tracking", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_session_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_record_lookup", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_record_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_time", table_name="audit_logs")
    op.drop_index("ix_audit_logs_operation_time", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_operation"), table_name="audit_logs")
    op.drop_index(
        "ix_audit_logs_old_values_gin",
        table_name="audit_logs",
        postgresql_using="gin",
        postgresql_ops={"old_values": "jsonb_path_ops"},
    )
    op.drop_index(
        "ix_audit_logs_new_values_gin",
        table_name="audit_logs",
        postgresql_using="gin",
        postgresql_ops={"new_values": "jsonb_path_ops"},
    )
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_correlation", table_name="audit_logs")
    op.drop_index(
        "ix_audit_logs_context_gin",
        table_name="audit_logs",
        postgresql_using="gin",
        postgresql_ops={"additional_context": "jsonb_path_ops"},
    )
    op.drop_index(op.f("ix_audit_logs_category"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_audit_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(
        op.f("ix_audit_configurations_table_name"), table_name="audit_configurations"
    )
    op.drop_index(
        op.f("ix_audit_configurations_organization_id"),
        table_name="audit_configurations",
    )
    op.drop_index(
        op.f("ix_audit_configurations_operation"), table_name="audit_configurations"
    )
    op.drop_index(op.f("ix_audit_configurations_id"), table_name="audit_configurations")
    op.drop_index("ix_audit_config_unique", table_name="audit_configurations")
    op.drop_index("ix_audit_config_lookup", table_name="audit_configurations")
    op.drop_table("audit_configurations")
    # ### end Alembic commands ###
