"""enhance_rbac_schema_for_multi_tenancy

Revision ID: 85832f9f86ce
Revises: 85f9e3f15142
Create Date: 2025-06-10 12:49:07.877331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85832f9f86ce"
down_revision: Union[str, None] = "85f9e3f15142"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "organization_id", name="_user_org_role_uc"),
    )
    op.create_index(op.f("ix_user_roles_id"), "user_roles", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_roles_organization_id"),
        "user_roles",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False
    )
    op.add_column(
        "permissions", sa.Column("organization_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "permissions", sa.Column("is_system_permission", sa.Boolean(), nullable=False)
    )
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=False)
    op.create_unique_constraint(
        "_permission_name_org_uc", "permissions", ["name", "organization_id"]
    )
    op.create_index(
        op.f("ix_permissions_organization_id"),
        "permissions",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "permissions", "organizations", ["organization_id"], ["id"]
    )
    op.add_column("roles", sa.Column("organization_id", sa.Integer(), nullable=True))
    op.add_column("roles", sa.Column("is_system_role", sa.Boolean(), nullable=False))
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_unique_constraint(
        "_role_name_org_uc", "roles", ["name", "organization_id"]
    )
    op.create_index(
        op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False
    )
    op.create_foreign_key(None, "roles", "organizations", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_constraint("_role_name_org_uc", "roles", type_="unique")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.drop_column("roles", "is_system_role")
    op.drop_column("roles", "organization_id")
    op.drop_constraint(None, "permissions", type_="foreignkey")
    op.drop_index(op.f("ix_permissions_organization_id"), table_name="permissions")
    op.drop_constraint("_permission_name_org_uc", "permissions", type_="unique")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.drop_column("permissions", "is_system_permission")
    op.drop_column("permissions", "organization_id")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_organization_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_id"), table_name="user_roles")
    op.drop_table("user_roles")
    # ### end Alembic commands ###
