"""implement_multi_tenancy_schema

Revision ID: 85f9e3f15142
Revises: d8b40ecdc203
Create Date: 2025-06-10 10:38:17.181211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85f9e3f15142"
down_revision: Union[str, None] = "d8b40ecdc203"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address_line1", sa.String(length=255), nullable=True),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("date_format", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("subscription_tier", sa.String(length=50), nullable=False),
        sa.Column("max_users", sa.Integer(), nullable=False),
        sa.Column("max_projects", sa.Integer(), nullable=False),
        sa.Column("max_clusters", sa.Integer(), nullable=False),
        sa.Column("storage_limit_gb", sa.Integer(), nullable=False),
        sa.Column("billing_email", sa.String(length=255), nullable=True),
        sa.Column("tax_id", sa.String(length=100), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("org_metadata", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_index(
        op.f("ix_organizations_name"), "organizations", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.add_column(
        "aws_accounts", sa.Column("organization_id", sa.Integer(), nullable=False)
    )
    op.drop_index(op.f("ix_aws_accounts_account_id"), table_name="aws_accounts")
    op.create_index(
        op.f("ix_aws_accounts_account_id"), "aws_accounts", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_aws_accounts_organization_id"),
        "aws_accounts",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "aws_accounts", "organizations", ["organization_id"], ["id"]
    )
    op.add_column(
        "clusters", sa.Column("organization_id", sa.Integer(), nullable=False)
    )
    op.drop_index(op.f("ix_clusters_cluster_id"), table_name="clusters")
    op.create_index(
        op.f("ix_clusters_cluster_id"), "clusters", ["cluster_id"], unique=False
    )
    op.create_index(
        op.f("ix_clusters_organization_id"),
        "clusters",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "clusters", "organizations", ["organization_id"], ["id"]
    )
    op.add_column(
        "projects", sa.Column("organization_id", sa.Integer(), nullable=False)
    )
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_index(
        op.f("ix_projects_organization_id"),
        "projects",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "projects", "organizations", ["organization_id"], ["id"]
    )
    op.add_column("teams", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.drop_index(op.f("ix_teams_slug"), table_name="teams")
    op.create_index(op.f("ix_teams_slug"), "teams", ["slug"], unique=False)
    op.create_index(
        op.f("ix_teams_organization_id"), "teams", ["organization_id"], unique=False
    )
    op.create_foreign_key(None, "teams", "organizations", ["organization_id"], ["id"])
    op.add_column("users", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=False)
    op.drop_index(op.f("ix_users_github_username"), table_name="users")
    op.create_index(
        op.f("ix_users_github_username"), "users", ["github_username"], unique=False
    )
    op.create_index(
        op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False
    )
    op.create_foreign_key(None, "users", "organizations", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_github_username"), table_name="users")
    op.create_index(
        op.f("ix_users_github_username"), "users", ["github_username"], unique=True
    )
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "organization_id")
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.drop_index(op.f("ix_teams_organization_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_slug"), table_name="teams")
    op.create_index(op.f("ix_teams_slug"), "teams", ["slug"], unique=True)
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=True)
    op.drop_column("teams", "organization_id")
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.drop_column("projects", "organization_id")
    op.drop_constraint(None, "clusters", type_="foreignkey")
    op.drop_index(op.f("ix_clusters_organization_id"), table_name="clusters")
    op.drop_index(op.f("ix_clusters_cluster_id"), table_name="clusters")
    op.create_index(
        op.f("ix_clusters_cluster_id"), "clusters", ["cluster_id"], unique=True
    )
    op.drop_column("clusters", "organization_id")
    op.drop_constraint(None, "aws_accounts", type_="foreignkey")
    op.drop_index(op.f("ix_aws_accounts_organization_id"), table_name="aws_accounts")
    op.drop_index(op.f("ix_aws_accounts_account_id"), table_name="aws_accounts")
    op.create_index(
        op.f("ix_aws_accounts_account_id"), "aws_accounts", ["account_id"], unique=True
    )
    op.drop_column("aws_accounts", "organization_id")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
