"""implement_time_series_data_modeling_final

Revision ID: b521a10e8182
Revises: 85832f9f86ce
Create Date: 2025-06-10 19:19:05.746729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b521a10e8182"
down_revision: Union[str, None] = "85832f9f86ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_timestamp", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_name", sa.String(length=255), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("triggered_by", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("resolved_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column(
            "affected_services", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("impact_level", sa.String(length=20), nullable=True),
        sa.Column("downtime_duration", sa.Integer(), nullable=True),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parent_event_id", sa.Integer(), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column(
            "event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        "ix_events_cluster_time", "events", ["cluster_id", "timestamp"], unique=False
    )
    op.create_index("ix_events_correlation", "events", ["correlation_id"], unique=False)
    op.create_index(
        op.f("ix_events_correlation_id"), "events", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_events_environment"), "events", ["environment"], unique=False
    )
    op.create_index(
        "ix_events_event_data_gin",
        "events",
        ["event_data"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"event_data": "jsonb_path_ops"},
    )
    op.create_index(
        op.f("ix_events_event_name"), "events", ["event_name"], unique=False
    )
    op.create_index(
        op.f("ix_events_event_type"), "events", ["event_type"], unique=False
    )
    op.create_index(
        "ix_events_labels_gin",
        "events",
        ["labels"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"labels": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_events_org_time_type",
        "events",
        ["organization_id", "timestamp", "event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_events_project_time", "events", ["project_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_events_service_name"), "events", ["service_name"], unique=False
    )
    op.create_index(
        "ix_events_service_time", "events", ["service_name", "timestamp"], unique=False
    )
    op.create_index(
        "ix_events_severity_time", "events", ["severity", "timestamp"], unique=False
    )
    op.create_index(
        "ix_events_status_time", "events", ["status", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_events_timestamp"), "events", ["timestamp"], unique=False)
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("log_level", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("raw_log", sa.Text(), nullable=True),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("application_name", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column("instance_id", sa.String(length=255), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("span_id", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("container_name", sa.String(length=255), nullable=True),
        sa.Column("pod_name", sa.String(length=255), nullable=True),
        sa.Column("namespace", sa.String(length=255), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "structured_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column(
            "additional_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("parsed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("enriched_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_log_entries_app_time",
        "log_entries",
        ["application_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_entries_application_name"),
        "log_entries",
        ["application_name"],
        unique=False,
    )
    op.create_index(
        "ix_log_entries_container_time",
        "log_entries",
        ["container_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_entries_environment"), "log_entries", ["environment"], unique=False
    )
    op.create_index(op.f("ix_log_entries_host"), "log_entries", ["host"], unique=False)
    op.create_index(
        "ix_log_entries_host_time", "log_entries", ["host", "timestamp"], unique=False
    )
    op.create_index(
        "ix_log_entries_labels_gin",
        "log_entries",
        ["labels"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"labels": "jsonb_path_ops"},
    )
    op.create_index(
        op.f("ix_log_entries_log_level"), "log_entries", ["log_level"], unique=False
    )
    op.create_index(
        "ix_log_entries_org_time_level",
        "log_entries",
        ["organization_id", "timestamp", "log_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_entries_organization_id"),
        "log_entries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_log_entries_pod_time",
        "log_entries",
        ["pod_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_entries_request_id"), "log_entries", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_log_entries_service_name"),
        "log_entries",
        ["service_name"],
        unique=False,
    )
    op.create_index(
        "ix_log_entries_service_time",
        "log_entries",
        ["service_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_log_entries_source"), "log_entries", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_log_entries_source_id"), "log_entries", ["source_id"], unique=False
    )
    op.create_index(
        "ix_log_entries_source_time",
        "log_entries",
        ["source", "source_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_log_entries_structured_gin",
        "log_entries",
        ["structured_data"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"structured_data": "jsonb_path_ops"},
    )
    op.create_index(
        op.f("ix_log_entries_timestamp"), "log_entries", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_log_entries_trace_id", "log_entries", ["trace_id"], unique=False
    )
    op.create_table(
        "metric_summaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("time_bucket", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("resolution", sa.String(length=20), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("metric_type", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("avg_value", sa.Float(), nullable=True),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("sum_value", sa.Float(), nullable=True),
        sa.Column("count_value", sa.Integer(), nullable=False),
        sa.Column("stddev_value", sa.Float(), nullable=True),
        sa.Column("percentile_50", sa.Float(), nullable=True),
        sa.Column("percentile_95", sa.Float(), nullable=True),
        sa.Column("percentile_99", sa.Float(), nullable=True),
        sa.Column("data_points", sa.Integer(), nullable=False),
        sa.Column("interpolated_points", sa.Integer(), nullable=False),
        sa.Column("missing_points", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_summaries_cluster_bucket",
        "metric_summaries",
        ["cluster_id", "time_bucket"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_summaries_environment"),
        "metric_summaries",
        ["environment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_summaries_metric_name"),
        "metric_summaries",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        "ix_metric_summaries_name_bucket",
        "metric_summaries",
        ["metric_name", "time_bucket"],
        unique=False,
    )
    op.create_index(
        "ix_metric_summaries_org_bucket_resolution",
        "metric_summaries",
        ["organization_id", "time_bucket", "resolution"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_summaries_organization_id"),
        "metric_summaries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_metric_summaries_project_bucket",
        "metric_summaries",
        ["project_id", "time_bucket"],
        unique=False,
    )
    op.create_index(
        "ix_metric_summaries_service_bucket",
        "metric_summaries",
        ["service_name", "time_bucket"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_summaries_service_name"),
        "metric_summaries",
        ["service_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_summaries_time_bucket"),
        "metric_summaries",
        ["time_bucket"],
        unique=False,
    )
    op.create_table(
        "metric_thresholds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("warning_min", sa.Float(), nullable=True),
        sa.Column("warning_max", sa.Float(), nullable=True),
        sa.Column("critical_min", sa.Float(), nullable=True),
        sa.Column("critical_max", sa.Float(), nullable=True),
        sa.Column("evaluation_window", sa.String(length=50), nullable=False),
        sa.Column("consecutive_violations", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "threshold_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_thresholds_active", "metric_thresholds", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_metric_thresholds_environment"),
        "metric_thresholds",
        ["environment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_thresholds_metric_name"),
        "metric_thresholds",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        "ix_metric_thresholds_org_metric",
        "metric_thresholds",
        ["organization_id", "metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_thresholds_organization_id"),
        "metric_thresholds",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_metric_thresholds_service_metric",
        "metric_thresholds",
        ["service_name", "metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metric_thresholds_service_name"),
        "metric_thresholds",
        ["service_name"],
        unique=False,
    )
    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("metric_type", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "additional_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("is_interpolated", sa.Boolean(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metrics_cluster_time", "metrics", ["cluster_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_metrics_environment"), "metrics", ["environment"], unique=False
    )
    op.create_index(
        "ix_metrics_labels_gin",
        "metrics",
        ["labels"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"labels": "jsonb_path_ops"},
    )
    op.create_index(
        op.f("ix_metrics_metric_name"), "metrics", ["metric_name"], unique=False
    )
    op.create_index(
        "ix_metrics_org_time_name",
        "metrics",
        ["organization_id", "timestamp", "metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metrics_organization_id"), "metrics", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_metrics_project_time", "metrics", ["project_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_metrics_service_env_time",
        "metrics",
        ["service_name", "environment", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metrics_service_name"), "metrics", ["service_name"], unique=False
    )
    op.create_index(
        op.f("ix_metrics_source_id"), "metrics", ["source_id"], unique=False
    )
    op.create_index(
        "ix_metrics_source_time",
        "metrics",
        ["source", "source_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_metrics_tags_gin",
        "metrics",
        ["tags"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"tags": "jsonb_path_ops"},
    )
    op.create_index(
        op.f("ix_metrics_timestamp"), "metrics", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metrics_timestamp"), table_name="metrics")
    op.drop_index(
        "ix_metrics_tags_gin",
        table_name="metrics",
        postgresql_using="gin",
        postgresql_ops={"tags": "jsonb_path_ops"},
    )
    op.drop_index("ix_metrics_source_time", table_name="metrics")
    op.drop_index(op.f("ix_metrics_source_id"), table_name="metrics")
    op.drop_index(op.f("ix_metrics_service_name"), table_name="metrics")
    op.drop_index("ix_metrics_service_env_time", table_name="metrics")
    op.drop_index("ix_metrics_project_time", table_name="metrics")
    op.drop_index(op.f("ix_metrics_organization_id"), table_name="metrics")
    op.drop_index("ix_metrics_org_time_name", table_name="metrics")
    op.drop_index(op.f("ix_metrics_metric_name"), table_name="metrics")
    op.drop_index(
        "ix_metrics_labels_gin",
        table_name="metrics",
        postgresql_using="gin",
        postgresql_ops={"labels": "jsonb_path_ops"},
    )
    op.drop_index(op.f("ix_metrics_environment"), table_name="metrics")
    op.drop_index("ix_metrics_cluster_time", table_name="metrics")
    op.drop_table("metrics")
    op.drop_index(
        op.f("ix_metric_thresholds_service_name"), table_name="metric_thresholds"
    )
    op.drop_index("ix_metric_thresholds_service_metric", table_name="metric_thresholds")
    op.drop_index(
        op.f("ix_metric_thresholds_organization_id"), table_name="metric_thresholds"
    )
    op.drop_index("ix_metric_thresholds_org_metric", table_name="metric_thresholds")
    op.drop_index(
        op.f("ix_metric_thresholds_metric_name"), table_name="metric_thresholds"
    )
    op.drop_index(
        op.f("ix_metric_thresholds_environment"), table_name="metric_thresholds"
    )
    op.drop_index("ix_metric_thresholds_active", table_name="metric_thresholds")
    op.drop_table("metric_thresholds")
    op.drop_index(
        op.f("ix_metric_summaries_time_bucket"), table_name="metric_summaries"
    )
    op.drop_index(
        op.f("ix_metric_summaries_service_name"), table_name="metric_summaries"
    )
    op.drop_index("ix_metric_summaries_service_bucket", table_name="metric_summaries")
    op.drop_index("ix_metric_summaries_project_bucket", table_name="metric_summaries")
    op.drop_index(
        op.f("ix_metric_summaries_organization_id"), table_name="metric_summaries"
    )
    op.drop_index(
        "ix_metric_summaries_org_bucket_resolution", table_name="metric_summaries"
    )
    op.drop_index("ix_metric_summaries_name_bucket", table_name="metric_summaries")
    op.drop_index(
        op.f("ix_metric_summaries_metric_name"), table_name="metric_summaries"
    )
    op.drop_index(
        op.f("ix_metric_summaries_environment"), table_name="metric_summaries"
    )
    op.drop_index("ix_metric_summaries_cluster_bucket", table_name="metric_summaries")
    op.drop_table("metric_summaries")
    op.drop_index("ix_log_entries_trace_id", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_timestamp"), table_name="log_entries")
    op.drop_index(
        "ix_log_entries_structured_gin",
        table_name="log_entries",
        postgresql_using="gin",
        postgresql_ops={"structured_data": "jsonb_path_ops"},
    )
    op.drop_index("ix_log_entries_source_time", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_source_id"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_source"), table_name="log_entries")
    op.drop_index("ix_log_entries_service_time", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_service_name"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_request_id"), table_name="log_entries")
    op.drop_index("ix_log_entries_pod_time", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_organization_id"), table_name="log_entries")
    op.drop_index("ix_log_entries_org_time_level", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_log_level"), table_name="log_entries")
    op.drop_index(
        "ix_log_entries_labels_gin",
        table_name="log_entries",
        postgresql_using="gin",
        postgresql_ops={"labels": "jsonb_path_ops"},
    )
    op.drop_index("ix_log_entries_host_time", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_host"), table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_environment"), table_name="log_entries")
    op.drop_index("ix_log_entries_container_time", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_application_name"), table_name="log_entries")
    op.drop_index("ix_log_entries_app_time", table_name="log_entries")
    op.drop_table("log_entries")
    op.drop_index(op.f("ix_events_timestamp"), table_name="events")
    op.drop_index("ix_events_status_time", table_name="events")
    op.drop_index("ix_events_severity_time", table_name="events")
    op.drop_index("ix_events_service_time", table_name="events")
    op.drop_index(op.f("ix_events_service_name"), table_name="events")
    op.drop_index("ix_events_project_time", table_name="events")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_index("ix_events_org_time_type", table_name="events")
    op.drop_index(
        "ix_events_labels_gin",
        table_name="events",
        postgresql_using="gin",
        postgresql_ops={"labels": "jsonb_path_ops"},
    )
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_event_name"), table_name="events")
    op.drop_index(
        "ix_events_event_data_gin",
        table_name="events",
        postgresql_using="gin",
        postgresql_ops={"event_data": "jsonb_path_ops"},
    )
    op.drop_index(op.f("ix_events_environment"), table_name="events")
    op.drop_index(op.f("ix_events_correlation_id"), table_name="events")
    op.drop_index("ix_events_correlation", table_name="events")
    op.drop_index("ix_events_cluster_time", table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
