"""Initial database schema migration

Revision ID: d8b40ecdc203
Revises:
Create Date: 2025-06-10 01:43:32.820357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8b40ecdc203"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "CREATE_USERS",
                "UPDATE_USERS",
                "DELETE_USERS",
                "VIEW_USERS",
                "CREATE_TEAMS",
                "UPDATE_TEAMS",
                "DELETE_TEAMS",
                "VIEW_TEAMS",
                "MANAGE_TEAM_MEMBERS",
                "CREATE_PROJECTS",
                "UPDATE_PROJECTS",
                "DELETE_PROJECTS",
                "VIEW_PROJECTS",
                "VIEW_INFRASTRUCTURE",
                "MANAGE_INFRASTRUCTURE",
                "DEPLOY_INFRASTRUCTURE",
                "VIEW_PIPELINES",
                "TRIGGER_PIPELINES",
                "MANAGE_PIPELINES",
                "VIEW_AUTOMATION",
                "TRIGGER_AUTOMATION",
                "MANAGE_AUTOMATION",
                "VIEW_ALERTS",
                "ACKNOWLEDGE_ALERTS",
                "RESOLVE_ALERTS",
                "MANAGE_ALERTS",
                "VIEW_COSTS",
                "MANAGE_COST_BUDGETS",
                "VIEW_ROLES",
                "MANAGE_ROLES",
                "VIEW_SYSTEM_LOGS",
                "MANAGE_SYSTEM_SETTINGS",
                name="permissiontype",
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "SUPER_ADMIN",
                "ADMIN",
                "MANAGER",
                "ENGINEER",
                "VIEWER",
                name="systemrole",
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_id", sa.String(), nullable=False),
        sa.Column("github_username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("blog", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("github_access_token", sa.String(), nullable=True),
        sa.Column("github_scope", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.create_index(
        op.f("ix_users_github_username"), "users", ["github_username"], unique=True
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("max_members", sa.Integer(), nullable=False),
        sa.Column(
            "default_role",
            sa.Enum("OWNER", "ADMIN", "MEMBER", "VIEWER", name="teamrole"),
            nullable=False,
        ),
        sa.Column("settings", sa.Text(), nullable=True),
        sa.Column("permissions", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_id"), "teams", ["id"], unique=False)
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=True)
    op.create_index(op.f("ix_teams_slug"), "teams", ["slug"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("repository_url", sa.String(), nullable=True),
        sa.Column("repository_provider", sa.String(), nullable=True),
        sa.Column("default_branch", sa.String(), nullable=False),
        sa.Column("settings", sa.Text(), nullable=True),
        sa.Column("environment_config", sa.Text(), nullable=True),
        sa.Column("notification_config", sa.Text(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.create_table(
        "team_memberships",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "MEMBER", "VIEWER", name="teamrole"),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    op.create_table(
        "user_teams",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "MEMBER", "VIEWER", name="teamrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "team_id"),
    )
    op.create_table(
        "automation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("automation_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "automation_type",
            sa.Enum(
                "PLAYBOOK", "ROLE", "TASK", "AD_HOC", "TOWER_JOB", name="automationtype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                "PARTIAL_SUCCESS",
                name="automationstatus",
            ),
            nullable=False,
        ),
        sa.Column("playbook_name", sa.String(), nullable=True),
        sa.Column("inventory_name", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("ansible_version", sa.String(), nullable=True),
        sa.Column("python_version", sa.String(), nullable=True),
        sa.Column("command_line", sa.Text(), nullable=True),
        sa.Column("working_directory", sa.String(), nullable=True),
        sa.Column("total_hosts", sa.Integer(), nullable=True),
        sa.Column("successful_hosts", sa.Integer(), nullable=True),
        sa.Column("failed_hosts", sa.Integer(), nullable=True),
        sa.Column("unreachable_hosts", sa.Integer(), nullable=True),
        sa.Column("skipped_hosts", sa.Integer(), nullable=True),
        sa.Column("total_tasks", sa.Integer(), nullable=True),
        sa.Column("successful_tasks", sa.Integer(), nullable=True),
        sa.Column("failed_tasks", sa.Integer(), nullable=True),
        sa.Column("skipped_tasks", sa.Integer(), nullable=True),
        sa.Column("changed_tasks", sa.Integer(), nullable=True),
        sa.Column("host_results", sa.Text(), nullable=True),
        sa.Column("task_results", sa.Text(), nullable=True),
        sa.Column("play_results", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("log_output", sa.Text(), nullable=True),
        sa.Column("log_url", sa.String(), nullable=True),
        sa.Column("extra_vars", sa.Text(), nullable=True),
        sa.Column("vault_password_file", sa.String(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("skip_tags", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.String(), nullable=True),
        sa.Column("repository_branch", sa.String(), nullable=True),
        sa.Column("commit_sha", sa.String(), nullable=True),
        sa.Column("playbook_path", sa.String(), nullable=True),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("target_group", sa.String(), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("check_mode", sa.Boolean(), nullable=False),
        sa.Column("setup_time_seconds", sa.Float(), nullable=True),
        sa.Column("execution_time_seconds", sa.Float(), nullable=True),
        sa.Column("teardown_time_seconds", sa.Float(), nullable=True),
        sa.Column("coverage_percentage", sa.Float(), nullable=True),
        sa.Column("automation_score", sa.Float(), nullable=True),
        sa.Column("triggered_by_user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("is_scheduled", sa.Boolean(), nullable=False),
        sa.Column("is_manual_trigger", sa.Boolean(), nullable=False),
        sa.Column("has_failures", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_automation_runs_automation_id"),
        "automation_runs",
        ["automation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_automation_runs_id"), "automation_runs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_automation_runs_name"), "automation_runs", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_automation_runs_playbook_name"),
        "automation_runs",
        ["playbook_name"],
        unique=False,
    )
    op.create_table(
        "aws_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(length=12), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column("access_key_id", sa.String(length=255), nullable=False),
        sa.Column("secret_access_key", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aws_accounts_account_id"), "aws_accounts", ["account_id"], unique=True
    )
    op.create_index(op.f("ix_aws_accounts_id"), "aws_accounts", ["id"], unique=False)
    op.create_table(
        "clusters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "HEALTHY",
                "WARNING",
                "CRITICAL",
                "UNKNOWN",
                "OFFLINE",
                name="clusterstatus",
            ),
            nullable=False,
        ),
        sa.Column("health_score", sa.Float(), nullable=True),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("zone", sa.String(), nullable=True),
        sa.Column("endpoint_url", sa.String(), nullable=True),
        sa.Column("total_nodes", sa.Integer(), nullable=True),
        sa.Column("ready_nodes", sa.Integer(), nullable=True),
        sa.Column("not_ready_nodes", sa.Integer(), nullable=True),
        sa.Column("node_details", sa.Text(), nullable=True),
        sa.Column("total_pods", sa.Integer(), nullable=True),
        sa.Column("running_pods", sa.Integer(), nullable=True),
        sa.Column("pending_pods", sa.Integer(), nullable=True),
        sa.Column("failed_pods", sa.Integer(), nullable=True),
        sa.Column("total_cpu_cores", sa.Float(), nullable=True),
        sa.Column("allocatable_cpu_cores", sa.Float(), nullable=True),
        sa.Column("used_cpu_cores", sa.Float(), nullable=True),
        sa.Column("cpu_utilization_percent", sa.Float(), nullable=True),
        sa.Column("total_memory_gb", sa.Float(), nullable=True),
        sa.Column("allocatable_memory_gb", sa.Float(), nullable=True),
        sa.Column("used_memory_gb", sa.Float(), nullable=True),
        sa.Column("memory_utilization_percent", sa.Float(), nullable=True),
        sa.Column("total_storage_gb", sa.Float(), nullable=True),
        sa.Column("used_storage_gb", sa.Float(), nullable=True),
        sa.Column("storage_utilization_percent", sa.Float(), nullable=True),
        sa.Column("network_in_bytes", sa.Float(), nullable=True),
        sa.Column("network_out_bytes", sa.Float(), nullable=True),
        sa.Column("network_errors", sa.Integer(), nullable=True),
        sa.Column("total_namespaces", sa.Integer(), nullable=True),
        sa.Column("total_services", sa.Integer(), nullable=True),
        sa.Column("total_ingresses", sa.Integer(), nullable=True),
        sa.Column("total_deployments", sa.Integer(), nullable=True),
        sa.Column("total_statefulsets", sa.Integer(), nullable=True),
        sa.Column("total_daemonsets", sa.Integer(), nullable=True),
        sa.Column("config_data", sa.Text(), nullable=True),
        sa.Column("labels", sa.Text(), nullable=True),
        sa.Column("annotations", sa.Text(), nullable=True),
        sa.Column("monitoring_enabled", sa.Boolean(), nullable=False),
        sa.Column("prometheus_endpoint", sa.String(), nullable=True),
        sa.Column("grafana_dashboard_url", sa.String(), nullable=True),
        sa.Column("log_aggregation_url", sa.String(), nullable=True),
        sa.Column("cpu_alert_threshold", sa.Float(), nullable=False),
        sa.Column("memory_alert_threshold", sa.Float(), nullable=False),
        sa.Column("storage_alert_threshold", sa.Float(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clusters_cluster_id"), "clusters", ["cluster_id"], unique=True
    )
    op.create_index(op.f("ix_clusters_id"), "clusters", ["id"], unique=False)
    op.create_index(op.f("ix_clusters_name"), "clusters", ["name"], unique=False)
    op.create_table(
        "infrastructure_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("change_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum(
                "CREATE", "UPDATE", "DELETE", "REPLACE", "NO_CHANGE", name="changetype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "APPLYING",
                "APPLIED",
                "FAILED",
                "CANCELLED",
                "DESTROYED",
                "DESTROYING",
                name="changestatus",
            ),
            nullable=False,
        ),
        sa.Column("terraform_version", sa.String(), nullable=True),
        sa.Column("workspace", sa.String(), nullable=True),
        sa.Column(
            "resource_type",
            sa.Enum(
                "COMPUTE",
                "NETWORK",
                "STORAGE",
                "DATABASE",
                "SECURITY",
                "IAM",
                "MONITORING",
                "OTHER",
                name="resourcetype",
            ),
            nullable=True,
        ),
        sa.Column("resource_name", sa.String(), nullable=False),
        sa.Column("resource_address", sa.String(), nullable=False),
        sa.Column("provider_name", sa.String(), nullable=True),
        sa.Column("plan_summary", sa.Text(), nullable=True),
        sa.Column("plan_json", sa.Text(), nullable=True),
        sa.Column("diff_output", sa.Text(), nullable=True),
        sa.Column("planned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("availability_zone", sa.String(), nullable=True),
        sa.Column("repository_url", sa.String(), nullable=True),
        sa.Column("repository_branch", sa.String(), nullable=True),
        sa.Column("commit_sha", sa.String(), nullable=True),
        sa.Column("terraform_config_path", sa.String(), nullable=True),
        sa.Column("resource_config", sa.Text(), nullable=True),
        sa.Column("previous_config", sa.Text(), nullable=True),
        sa.Column("variables", sa.Text(), nullable=True),
        sa.Column("estimated_cost_change", sa.Float(), nullable=True),
        sa.Column("risk_level", sa.String(), nullable=True),
        sa.Column("impact_scope", sa.String(), nullable=True),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("approved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_comment", sa.Text(), nullable=True),
        sa.Column("resources_to_add", sa.Integer(), nullable=False),
        sa.Column("resources_to_change", sa.Integer(), nullable=False),
        sa.Column("resources_to_destroy", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("apply_log", sa.Text(), nullable=True),
        sa.Column("state_file_url", sa.String(), nullable=True),
        sa.Column("plan_file_url", sa.String(), nullable=True),
        sa.Column("compliance_tags", sa.Text(), nullable=True),
        sa.Column("resource_tags", sa.Text(), nullable=True),
        sa.Column("triggered_by_user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("is_automated", sa.Boolean(), nullable=False),
        sa.Column("is_rollback", sa.Boolean(), nullable=False),
        sa.Column("is_dry_run", sa.Boolean(), nullable=False),
        sa.Column("affects_production", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_infrastructure_changes_change_id"),
        "infrastructure_changes",
        ["change_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_infrastructure_changes_commit_sha"),
        "infrastructure_changes",
        ["commit_sha"],
        unique=False,
    )
    op.create_index(
        op.f("ix_infrastructure_changes_environment"),
        "infrastructure_changes",
        ["environment"],
        unique=False,
    )
    op.create_index(
        op.f("ix_infrastructure_changes_id"),
        "infrastructure_changes",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_infrastructure_changes_name"),
        "infrastructure_changes",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_infrastructure_changes_resource_name"),
        "infrastructure_changes",
        ["resource_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_infrastructure_changes_workspace"),
        "infrastructure_changes",
        ["workspace"],
        unique=False,
    )
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notification_id", sa.String(), nullable=False),
        sa.Column("digest_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("recipient_address", sa.String(), nullable=False),
        sa.Column("notification_type", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("template_name", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "DELIVERED",
                "FAILED",
                "BOUNCED",
                "REJECTED",
                name="deliverystatus",
            ),
            nullable=False,
        ),
        sa.Column("delivery_attempts", sa.Integer(), nullable=False),
        sa.Column("last_delivery_attempt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("provider_message_id", sa.String(), nullable=True),
        sa.Column("provider_response", sa.Text(), nullable=True),
        sa.Column("notification_metadata", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(), nullable=True),
        sa.Column("deduplication_key", sa.String(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_logs_channel"),
        "notification_logs",
        ["channel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_deduplication_key"),
        "notification_logs",
        ["deduplication_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_digest_id"),
        "notification_logs",
        ["digest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_id"), "notification_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_logs_notification_id"),
        "notification_logs",
        ["notification_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_notification_logs_notification_type"),
        "notification_logs",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_user_id"),
        "notification_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "ALERT_CRITICAL",
                "ALERT_HIGH",
                "ALERT_MEDIUM",
                "ALERT_LOW",
                "PIPELINE_SUCCESS",
                "PIPELINE_FAILURE",
                "DEPLOYMENT_SUCCESS",
                "DEPLOYMENT_FAILURE",
                "INFRASTRUCTURE_CHANGE",
                "AUTOMATION_RUN",
                "TEAM_ACTIVITY",
                "SYSTEM_MAINTENANCE",
                "DIGEST_DAILY",
                "DIGEST_WEEKLY",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum(
                "EMAIL",
                "SLACK",
                "WEBHOOK",
                "SMS",
                "TEAMS",
                "DISCORD",
                name="notificationchannel",
            ),
            nullable=False,
        ),
        sa.Column(
            "frequency",
            sa.Enum(
                "IMMEDIATE",
                "HOURLY",
                "DAILY",
                "WEEKLY",
                "NEVER",
                name="notificationfrequency",
            ),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("channel_settings", sa.Text(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("quiet_hours_start", sa.String(), nullable=True),
        sa.Column("quiet_hours_end", sa.String(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_preferences_id"),
        "notification_preferences",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_notification_type"),
        "notification_preferences",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "pipelines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pipeline_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "pipeline_type",
            sa.Enum(
                "BUILD",
                "TEST",
                "DEPLOY",
                "RELEASE",
                "ROLLBACK",
                "SCHEDULED",
                name="pipelinetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="pipelinestatus",
            ),
            nullable=False,
        ),
        sa.Column("branch", sa.String(), nullable=False),
        sa.Column("commit_sha", sa.String(), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("build_number", sa.Integer(), nullable=True),
        sa.Column("workflow_name", sa.String(), nullable=True),
        sa.Column("job_name", sa.String(), nullable=True),
        sa.Column("repository_url", sa.String(), nullable=False),
        sa.Column("repository_name", sa.String(), nullable=False),
        sa.Column("repository_owner", sa.String(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("log_url", sa.String(), nullable=True),
        sa.Column("artifacts_url", sa.String(), nullable=True),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("config_data", sa.Text(), nullable=True),
        sa.Column("labels", sa.Text(), nullable=True),
        sa.Column("triggered_by_user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("queue_time_seconds", sa.Float(), nullable=True),
        sa.Column("setup_time_seconds", sa.Float(), nullable=True),
        sa.Column("execution_time_seconds", sa.Float(), nullable=True),
        sa.Column("teardown_time_seconds", sa.Float(), nullable=True),
        sa.Column("cpu_usage_percent", sa.Float(), nullable=True),
        sa.Column("memory_usage_mb", sa.Float(), nullable=True),
        sa.Column("storage_usage_mb", sa.Float(), nullable=True),
        sa.Column("is_production_deploy", sa.Boolean(), nullable=False),
        sa.Column("is_rollback", sa.Boolean(), nullable=False),
        sa.Column("is_scheduled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipelines_branch"), "pipelines", ["branch"], unique=False)
    op.create_index(
        op.f("ix_pipelines_commit_sha"), "pipelines", ["commit_sha"], unique=False
    )
    op.create_index(op.f("ix_pipelines_id"), "pipelines", ["id"], unique=False)
    op.create_index(op.f("ix_pipelines_name"), "pipelines", ["name"], unique=False)
    op.create_index(
        op.f("ix_pipelines_pipeline_id"), "pipelines", ["pipeline_id"], unique=True
    )
    op.create_index(
        op.f("ix_pipelines_repository_name"),
        "pipelines",
        ["repository_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipelines_repository_owner"),
        "pipelines",
        ["repository_owner"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="alertseverity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "ACKNOWLEDGED", "RESOLVED", "SUPPRESSED", name="alertstatus"
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("channels", sa.Text(), nullable=True),
        sa.Column("context_data", sa.Text(), nullable=True),
        sa.Column("labels", sa.Text(), nullable=True),
        sa.Column("annotations", sa.Text(), nullable=True),
        sa.Column("pipeline_id", sa.Integer(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("automation_run_id", sa.Integer(), nullable=True),
        sa.Column("infrastructure_change_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("acknowledged_by_user_id", sa.Integer(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_comment", sa.Text(), nullable=True),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["automation_run_id"],
            ["automation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["infrastructure_change_id"],
            ["infrastructure_changes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_alert_id"), "alerts", ["alert_id"], unique=True)
    op.create_index(op.f("ix_alerts_category"), "alerts", ["category"], unique=False)
    op.create_index(op.f("ix_alerts_id"), "alerts", ["id"], unique=False)
    op.create_index(op.f("ix_alerts_source"), "alerts", ["source"], unique=False)
    op.create_index(op.f("ix_alerts_title"), "alerts", ["title"], unique=False)
    op.create_table(
        "aws_cost_anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aws_account_id", sa.Integer(), nullable=False),
        sa.Column("anomaly_type", sa.String(length=50), nullable=False),
        sa.Column("detected_date", sa.Date(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("resource_identifier", sa.String(length=500), nullable=True),
        sa.Column("expected_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("actual_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("cost_variance", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "variance_percentage", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("detection_method", sa.String(length=100), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column(
            "threshold_breached", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.String(length=255), nullable=True),
        sa.Column("alert_sent", sa.Boolean(), nullable=False),
        sa.Column("alert_sent_at", sa.DateTime(), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aws_account_id"],
            ["aws_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aws_cost_anomalies_detected_date"),
        "aws_cost_anomalies",
        ["detected_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aws_cost_anomalies_id"), "aws_cost_anomalies", ["id"], unique=False
    )
    op.create_table(
        "aws_cost_budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aws_account_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("budget_type", sa.String(length=50), nullable=False),
        sa.Column("time_unit", sa.String(length=20), nullable=False),
        sa.Column("budget_limit", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("service_filters", sa.JSON(), nullable=True),
        sa.Column("region_filters", sa.JSON(), nullable=True),
        sa.Column("tag_filters", sa.JSON(), nullable=True),
        sa.Column("alert_thresholds", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aws_account_id"],
            ["aws_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aws_cost_budgets_id"), "aws_cost_budgets", ["id"], unique=False
    )
    op.create_table(
        "aws_cost_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aws_account_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("granularity", sa.String(length=20), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("usage_type", sa.String(length=255), nullable=True),
        sa.Column("operation", sa.String(length=255), nullable=True),
        sa.Column("linked_account_id", sa.String(length=12), nullable=True),
        sa.Column("instance_type", sa.String(length=100), nullable=True),
        sa.Column("unblended_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("blended_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "net_unblended_cost", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "net_blended_cost", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column("amortized_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("usage_quantity", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("usage_unit", sa.String(length=50), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aws_account_id"],
            ["aws_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aws_cost_data_end_date"), "aws_cost_data", ["end_date"], unique=False
    )
    op.create_index(op.f("ix_aws_cost_data_id"), "aws_cost_data", ["id"], unique=False)
    op.create_index(
        op.f("ix_aws_cost_data_region"), "aws_cost_data", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_aws_cost_data_service_name"),
        "aws_cost_data",
        ["service_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aws_cost_data_start_date"),
        "aws_cost_data",
        ["start_date"],
        unique=False,
    )
    op.create_table(
        "aws_cost_forecasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aws_account_id", sa.Integer(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("forecast_type", sa.String(length=50), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=True),
        sa.Column("predicted_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "confidence_interval_lower",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
        ),
        sa.Column(
            "confidence_interval_upper",
            sa.Numeric(precision=12, scale=4),
            nullable=True,
        ),
        sa.Column("confidence_level", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("model_type", sa.String(length=100), nullable=False),
        sa.Column("model_accuracy", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("training_period_days", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["aws_account_id"],
            ["aws_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aws_cost_forecasts_forecast_date"),
        "aws_cost_forecasts",
        ["forecast_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aws_cost_forecasts_id"), "aws_cost_forecasts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_aws_cost_forecasts_service_name"),
        "aws_cost_forecasts",
        ["service_name"],
        unique=False,
    )
    op.create_table(
        "aws_cost_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aws_account_id", sa.Integer(), nullable=False),
        sa.Column("summary_date", sa.Date(), nullable=False),
        sa.Column("summary_type", sa.String(length=20), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "total_usage_cost", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column("total_ri_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "total_savings_plans_cost",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column("top_services", sa.JSON(), nullable=True),
        sa.Column(
            "previous_period_cost", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column(
            "cost_change_amount", sa.Numeric(precision=12, scale=4), nullable=True
        ),
        sa.Column(
            "cost_change_percentage", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aws_account_id"],
            ["aws_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aws_cost_summaries_id"), "aws_cost_summaries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_aws_cost_summaries_summary_date"),
        "aws_cost_summaries",
        ["summary_date"],
        unique=False,
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pipeline_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("run_number", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "CANCELLED",
                "SKIPPED",
                name="pipelinestatus",
            ),
            nullable=False,
        ),
        sa.Column("branch", sa.String(), nullable=False),
        sa.Column("commit_sha", sa.String(), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("workflow_name", sa.String(), nullable=True),
        sa.Column("job_name", sa.String(), nullable=True),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("log_url", sa.String(), nullable=True),
        sa.Column("artifacts_url", sa.String(), nullable=True),
        sa.Column("test_results_url", sa.String(), nullable=True),
        sa.Column("queue_time_seconds", sa.Float(), nullable=True),
        sa.Column("setup_time_seconds", sa.Float(), nullable=True),
        sa.Column("execution_time_seconds", sa.Float(), nullable=True),
        sa.Column("teardown_time_seconds", sa.Float(), nullable=True),
        sa.Column("cpu_usage_percent", sa.Float(), nullable=True),
        sa.Column("memory_usage_mb", sa.Float(), nullable=True),
        sa.Column("storage_usage_mb", sa.Float(), nullable=True),
        sa.Column("config_data", sa.Text(), nullable=True),
        sa.Column("labels", sa.Text(), nullable=True),
        sa.Column("triggered_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_runs_branch"), "pipeline_runs", ["branch"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_runs_commit_sha"),
        "pipeline_runs",
        ["commit_sha"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_runs_external_id"),
        "pipeline_runs",
        ["external_id"],
        unique=False,
    )
    op.create_index(op.f("ix_pipeline_runs_id"), "pipeline_runs", ["id"], unique=False)
    op.create_index(
        op.f("ix_pipeline_runs_pipeline_id"),
        "pipeline_runs",
        ["pipeline_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_runs_pipeline_id"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_id"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_external_id"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_commit_sha"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_branch"), table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index(
        op.f("ix_aws_cost_summaries_summary_date"), table_name="aws_cost_summaries"
    )
    op.drop_index(op.f("ix_aws_cost_summaries_id"), table_name="aws_cost_summaries")
    op.drop_table("aws_cost_summaries")
    op.drop_index(
        op.f("ix_aws_cost_forecasts_service_name"), table_name="aws_cost_forecasts"
    )
    op.drop_index(op.f("ix_aws_cost_forecasts_id"), table_name="aws_cost_forecasts")
    op.drop_index(
        op.f("ix_aws_cost_forecasts_forecast_date"), table_name="aws_cost_forecasts"
    )
    op.drop_table("aws_cost_forecasts")
    op.drop_index(op.f("ix_aws_cost_data_start_date"), table_name="aws_cost_data")
    op.drop_index(op.f("ix_aws_cost_data_service_name"), table_name="aws_cost_data")
    op.drop_index(op.f("ix_aws_cost_data_region"), table_name="aws_cost_data")
    op.drop_index(op.f("ix_aws_cost_data_id"), table_name="aws_cost_data")
    op.drop_index(op.f("ix_aws_cost_data_end_date"), table_name="aws_cost_data")
    op.drop_table("aws_cost_data")
    op.drop_index(op.f("ix_aws_cost_budgets_id"), table_name="aws_cost_budgets")
    op.drop_table("aws_cost_budgets")
    op.drop_index(op.f("ix_aws_cost_anomalies_id"), table_name="aws_cost_anomalies")
    op.drop_index(
        op.f("ix_aws_cost_anomalies_detected_date"), table_name="aws_cost_anomalies"
    )
    op.drop_table("aws_cost_anomalies")
    op.drop_index(op.f("ix_alerts_title"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_source"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_category"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_pipelines_repository_owner"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_repository_name"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_pipeline_id"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_name"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_id"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_commit_sha"), table_name="pipelines")
    op.drop_index(op.f("ix_pipelines_branch"), table_name="pipelines")
    op.drop_table("pipelines")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"),
        table_name="notification_preferences",
    )
    op.drop_index(
        op.f("ix_notification_preferences_notification_type"),
        table_name="notification_preferences",
    )
    op.drop_index(
        op.f("ix_notification_preferences_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_notification_logs_user_id"), table_name="notification_logs")
    op.drop_index(
        op.f("ix_notification_logs_notification_type"), table_name="notification_logs"
    )
    op.drop_index(
        op.f("ix_notification_logs_notification_id"), table_name="notification_logs"
    )
    op.drop_index(op.f("ix_notification_logs_id"), table_name="notification_logs")
    op.drop_index(
        op.f("ix_notification_logs_digest_id"), table_name="notification_logs"
    )
    op.drop_index(
        op.f("ix_notification_logs_deduplication_key"), table_name="notification_logs"
    )
    op.drop_index(op.f("ix_notification_logs_channel"), table_name="notification_logs")
    op.drop_table("notification_logs")
    op.drop_index(
        op.f("ix_infrastructure_changes_workspace"), table_name="infrastructure_changes"
    )
    op.drop_index(
        op.f("ix_infrastructure_changes_resource_name"),
        table_name="infrastructure_changes",
    )
    op.drop_index(
        op.f("ix_infrastructure_changes_name"), table_name="infrastructure_changes"
    )
    op.drop_index(
        op.f("ix_infrastructure_changes_id"), table_name="infrastructure_changes"
    )
    op.drop_index(
        op.f("ix_infrastructure_changes_environment"),
        table_name="infrastructure_changes",
    )
    op.drop_index(
        op.f("ix_infrastructure_changes_commit_sha"),
        table_name="infrastructure_changes",
    )
    op.drop_index(
        op.f("ix_infrastructure_changes_change_id"), table_name="infrastructure_changes"
    )
    op.drop_table("infrastructure_changes")
    op.drop_index(op.f("ix_clusters_name"), table_name="clusters")
    op.drop_index(op.f("ix_clusters_id"), table_name="clusters")
    op.drop_index(op.f("ix_clusters_cluster_id"), table_name="clusters")
    op.drop_table("clusters")
    op.drop_index(op.f("ix_aws_accounts_id"), table_name="aws_accounts")
    op.drop_index(op.f("ix_aws_accounts_account_id"), table_name="aws_accounts")
    op.drop_table("aws_accounts")
    op.drop_index(
        op.f("ix_automation_runs_playbook_name"), table_name="automation_runs"
    )
    op.drop_index(op.f("ix_automation_runs_name"), table_name="automation_runs")
    op.drop_index(op.f("ix_automation_runs_id"), table_name="automation_runs")
    op.drop_index(
        op.f("ix_automation_runs_automation_id"), table_name="automation_runs"
    )
    op.drop_table("automation_runs")
    op.drop_table("user_teams")
    op.drop_table("team_memberships")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_teams_slug"), table_name="teams")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_index(op.f("ix_teams_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_github_username"), table_name="users")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
