"""add user_permissions table for direct user-permission assignments

Revision ID: e988b93edd68
Revises: 80bd6a3c3fa1
Create Date: 2025-06-14 19:09:53.205491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e988b93edd68"
down_revision: Union[str, None] = "80bd6a3c3fa1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "permission_id", "organization_id", name="_user_permission_uc"
        ),
    )
    op.create_index(
        op.f("ix_user_permissions_id"), "user_permissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_permissions_organization_id"),
        "user_permissions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_permissions_permission_id"),
        "user_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_permissions_user_id"),
        "user_permissions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_permissions_user_id"), table_name="user_permissions")
    op.drop_index(
        op.f("ix_user_permissions_permission_id"), table_name="user_permissions"
    )
    op.drop_index(
        op.f("ix_user_permissions_organization_id"), table_name="user_permissions"
    )
    op.drop_index(op.f("ix_user_permissions_id"), table_name="user_permissions")
    op.drop_table("user_permissions")
    # ### end Alembic commands ###
