# User schemas (existing)
from .user import UserBase, UserCreate, User, UserUpdate
from .token import Token, TokenPayload

# Role and Permission schemas
from .role import (
    Role,
    RoleCreate,
    RoleUpdate,
    RoleSummary,
    Permission,
    PermissionCreate,
    PermissionUpdate,
    PermissionSummary,
    RoleAssignment,
    RoleAssignmentResponse,
    PermissionCheck,
    PermissionCheckResponse,
    BulkRoleAssignment,
    BulkRoleAssignmentResponse,
    BulkPermissionUpdate,
    SystemRoleInfo,
    SystemRoleSetup,
    RoleHierarchy,
    UserRoleInfo,
    UserRoleUpdate,
    RoleStatistics,
    PermissionStatistics,
    RBACAnalytics,
)

# Pipeline schemas
from .pipeline import (
    PipelineBase,
    PipelineCreate,
    PipelineUpdate,
    PipelineRunBase,
    PipelineRunCreate,
    PipelineRunUpdate,
    PipelineRun,
    Pipeline,
    PipelineStats,
    PipelineWithStats,
    GitHubActionsData,
)

# Cluster schemas
from .cluster import (
    ClusterBase,
    ClusterCreate,
    ClusterUpdate,
    NodeMetrics,
    ClusterMetricsUpdate,
    ClusterNode,
    Cluster,
    ClusterHealth,
    ClusterWithHealth,
    ClusterStats,
    ClusterWithStats,
    KubernetesMetrics,
)

# Automation run schemas
from .automation_run import (
    AutomationRunBase,
    AutomationRunCreate,
    AutomationRunUpdate,
    HostResult,
    TaskResult,
    AutomationRun,
    AutomationRunSummary,
    AutomationRunWithSummary,
    AutomationStats,
    AnsibleCallbackData,
    AnsibleInventory,
    PlaybookValidation,
)

# Infrastructure change schemas
from .infrastructure_change import (
    InfrastructureChangeBase,
    InfrastructureChangeCreate,
    InfrastructureChangeUpdate,
    ResourceChange,
    TerraformPlan,
    CostEstimate,
    ApprovalRequest,
    InfrastructureChange,
    InfrastructureChangeWithPlan,
    ChangeStats,
    InfrastructureStats,
    TerraformState,
    DriftDetection,
    ComplianceCheck,
)

# Alert schemas
from .alert import (
    AlertBase,
    AlertCreate,
    AlertUpdate,
    AlertNotificationBase,
    AlertNotificationCreate,
    AlertNotificationUpdate,
    AlertNotification,
    Alert,
    AlertRule,
    AlertRuleCreate,
    AlertRuleUpdate,
    AlertStats,
    AlertSummary,
    AlertEscalation,
    AlertSuppression,
    SlackNotificationData,
    EmailNotificationData,
    WebhookNotificationData,
)

# Team schemas
from .team import (
    TeamBase,
    TeamCreate,
    TeamUpdate,
    TeamMemberBase,
    TeamMemberCreate,
    TeamMemberUpdate,
    TeamMember,
    Team,
    TeamWithMembers,
    TeamStats,
    TeamWithStats,
    TeamInvitation,
    TeamInvitationCreate,
    TeamInvitationUpdate,
    TeamPermissions,
    TeamSettings,
    TeamActivity,
    TeamProjectAccess,
)

# Project schemas
from .project import (
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    Project,
    ProjectSummary,
    ProjectStats,
    ProjectWithStats,
    ProjectResourceSummary,
    ProjectWithResources,
    ProjectAccess,
    ProjectAccessCreate,
    ProjectAccessUpdate,
    ProjectEnvironment,
    ProjectNotificationSettings,
    ProjectIntegration,
    ProjectIntegrationCreate,
    ProjectIntegrationUpdate,
    ProjectActivity,
    ProjectHealth,
    ProjectWithHealth,
)

# Common response models (new for enhanced documentation)
from .common import (
    ResponseStatus,
    HealthStatus,
    BaseResponse,
    SuccessResponse,
    ErrorResponse,
    PaginatedResponse,
    HealthCheckResponse,
    DetailedHealthCheckResponse,
    APIInfoResponse,
    CacheMetrics,
    APIPerformanceInfo,
    IDField,
    TimestampFields,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "User",
    "UserUpdate",
    "Token",
    "TokenPayload",
    # Role and Permission schemas
    "Role",
    "RoleCreate",
    "RoleUpdate",
    "RoleSummary",
    "Permission",
    "PermissionCreate",
    "PermissionUpdate",
    "PermissionSummary",
    "RoleAssignment",
    "RoleAssignmentResponse",
    "PermissionCheck",
    "PermissionCheckResponse",
    "BulkRoleAssignment",
    "BulkRoleAssignmentResponse",
    "BulkPermissionUpdate",
    "SystemRoleInfo",
    "SystemRoleSetup",
    "RoleHierarchy",
    "UserRoleInfo",
    "UserRoleUpdate",
    "RoleStatistics",
    "PermissionStatistics",
    "RBACAnalytics",
    # Pipeline schemas
    "PipelineBase",
    "PipelineCreate",
    "PipelineUpdate",
    "PipelineRunBase",
    "PipelineRunCreate",
    "PipelineRunUpdate",
    "PipelineRun",
    "Pipeline",
    "PipelineStats",
    "PipelineWithStats",
    "GitHubActionsData",
    # Cluster schemas
    "ClusterBase",
    "ClusterCreate",
    "ClusterUpdate",
    "NodeMetrics",
    "ClusterMetricsUpdate",
    "ClusterNode",
    "Cluster",
    "ClusterHealth",
    "ClusterWithHealth",
    "ClusterStats",
    "ClusterWithStats",
    "KubernetesMetrics",
    # Automation run schemas
    "AutomationRunBase",
    "AutomationRunCreate",
    "AutomationRunUpdate",
    "HostResult",
    "TaskResult",
    "AutomationRun",
    "AutomationRunSummary",
    "AutomationRunWithSummary",
    "AutomationStats",
    "AnsibleCallbackData",
    "AnsibleInventory",
    "PlaybookValidation",
    # Infrastructure change schemas
    "InfrastructureChangeBase",
    "InfrastructureChangeCreate",
    "InfrastructureChangeUpdate",
    "ResourceChange",
    "TerraformPlan",
    "CostEstimate",
    "ApprovalRequest",
    "InfrastructureChange",
    "InfrastructureChangeWithPlan",
    "ChangeStats",
    "InfrastructureStats",
    "TerraformState",
    "DriftDetection",
    "ComplianceCheck",
    # Alert schemas
    "AlertBase",
    "AlertCreate",
    "AlertUpdate",
    "AlertNotificationBase",
    "AlertNotificationCreate",
    "AlertNotificationUpdate",
    "AlertNotification",
    "Alert",
    "AlertRule",
    "AlertRuleCreate",
    "AlertRuleUpdate",
    "AlertStats",
    "AlertSummary",
    "AlertEscalation",
    "AlertSuppression",
    "SlackNotificationData",
    "EmailNotificationData",
    "WebhookNotificationData",
    # Team schemas
    "TeamBase",
    "TeamCreate",
    "TeamUpdate",
    "TeamMemberBase",
    "TeamMemberCreate",
    "TeamMemberUpdate",
    "TeamMember",
    "Team",
    "TeamWithMembers",
    "TeamStats",
    "TeamWithStats",
    "TeamInvitation",
    "TeamInvitationCreate",
    "TeamInvitationUpdate",
    "TeamPermissions",
    "TeamSettings",
    "TeamActivity",
    "TeamProjectAccess",
    # Project schemas
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "Project",
    "ProjectSummary",
    "ProjectStats",
    "ProjectWithStats",
    "ProjectResourceSummary",
    "ProjectWithResources",
    "ProjectAccess",
    "ProjectAccessCreate",
    "ProjectAccessUpdate",
    "ProjectEnvironment",
    "ProjectNotificationSettings",
    "ProjectIntegration",
    "ProjectIntegrationCreate",
    "ProjectIntegrationUpdate",
    "ProjectActivity",
    "ProjectHealth",
    "ProjectWithHealth",
    # Common response models
    "ResponseStatus",
    "HealthStatus",
    "BaseResponse",
    "SuccessResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "HealthCheckResponse",
    "DetailedHealthCheckResponse",
    "APIInfoResponse",
    "CacheMetrics",
    "APIPerformanceInfo",
    "IDField",
    "TimestampFields",
]
